---
- name: get namespace name
  hosts: localhost
  collections:
    - oracle.oci
  vars:
    ansible_python_interpreter: /usr/bin/python3.9
  tasks:
    - name: get namespace
      oracle.oci.oci_object_storage_namespace_facts:
      register: output
    - name: print namespace
      debug:
        msg: "{{ output }}"