plugin: oracle.oci.oci

# From all regions
regions: all

use_extra_vars: true

#Get from compartment
compartments:
- compartment_name: "oci_workshop"
  parent_compartment_ocid: ocid1.tenancy.oc1..aaaaaaaa75einznwt2yjxdynglaacav7xv5ouqcsm7af3xqqa5yulmcwvr3q

#Fetch Compute
fetch_compute_hosts: True

# Enable Cache
cache: yes
cache_plugin: jsonfile
cache_timeout: 7200
cache_connection: /tmp/oci-cache
cache_prefix: oci_

# Sets the inventory_hostname to either "display_name" or id
# "'display_name+'.oci.com'" has more preference than id
hostname_format_preferences:
  - "public_ip"
  - "private_ip"